### PR TITLE
Support for NDK r25

### PR DESCRIPTION
**Pull request by phR0ze**
Updated the Dockerfile to match and validated it builds and using it to build apks works as well with the commands below
```bash
docker build -t cargo-quad-apk:latest .
docker run --rm -v $(pwd):/root/src -w /root/src cargo-quad-apk:latest cargo quad-apk build --release
```

### CODE REVIEW

**Comment by phR0ze** [comment]
@not-fl3 I'm interested in writing some code using macroquad and getting this crate updated to support the latest NDK would be great

**Comment by not-fl3** [comment]
Thank you very much for the PR, impressive work!

**Comment by not-fl3** [comment]
> @not-fl3 I'm interested in writing some code using macroquad and getting this crate updated to support the latest NDK would be great

Did anything else got broken by the new NDK? I will test it soon myself, but will be happy to help if you already found some problems!

**Comment by phR0ze** [comment]
Thank you for the offer. I haven't seen anything else yet, but I'll be sure to reach out if I do.

**Pull request merged**
